# Generated by Django 2.2.2 on 2019-06-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0002_auto_20190617_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='destription',
            new_name='description',
        ),
    ]
