# Generated by Django 2.2.2 on 2019-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0003_auto_20190617_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='morefields',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
