# Generated by Django 2.2.2 on 2019-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0004_content_morefields'),
    ]

    operations = [
        migrations.CreateModel(
            name='numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('fact', models.IntegerField()),
            ],
        ),
    ]
