# Generated by Django 2.2.2 on 2019-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0005_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='fact',
            field=models.TextField(),
        ),
    ]
