# Generated by Django 2.2.2 on 2019-06-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0006_auto_20190619_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numbers',
            old_name='numbers',
            new_name='number',
        ),
    ]
