# Generated by Django 2.2.2 on 2019-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryout', '0007_auto_20190620_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.TextField()),
                ('city_id', models.TextField()),
            ],
        ),
    ]
