# Generated by Django 2.2.2 on 2019-06-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuff',
            new_name='content',
        ),
    ]
