# Generated by Django 2.2.2 on 2019-06-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIP', '0002_auto_20190617_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='content',
        ),
    ]
